#!/bin/sh

#========================================
# chnetconf - change network configuration
#             with dirs under netconfs
#
# Yoshihiro Kawamata, kaw@on.rim.or.jp
# $Id: chnetconf,v 1.11 2021/11/18 09:54:11 kaw Exp $
#========================================

# Copyright (c) 2006--2021
# Yoshihiro Kawamata
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#   * Neither the name of Yoshihiro Kawamata nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

confdir=/etc/netconfs

usage () {
    cat <<'EOT' >&2
Usage: $0 [-d netconf-name|-r|-f netconf-name] | [netconf-name]
   -d: don't perform /etc/netstart, relink files only
   -r: reset all network interfaces
   -f: force reconfiguration unless current conf doesn't exist
EOT
}

# reset all network interfaces
#
resetif () {
    for if in `ifconfig -a | egrep '^[a-z]' | cut -d: -f1`; do
        case "$if" in
            lo[0-9]*|enc[0-9]*|pflog[0-9]*)
                # make this if untouched
                ;;
            *)
                ifconfig $if down
                ifconfig $if -inet -inet6
                if ! ifconfig $if destroy 2>/dev/null; then
                    # physical device ... can't destroy
                    ifconfig $if | grep -q '^	groups: wlan' && ifconfig $if -nwid -nwkey -wpakey
                fi
                ;;
        esac
    done >/dev/null 2>&1
}

# parsing command line options
#
while getopts drf OPT; do
    case "$OPT" in
        d) relink_only=yes;;
        r) removeif_only=yes;;
        f) force_setup=yes;;
        *) usage
           exit;;
    esac
done
shift $((OPTIND - 1))

cd /etc || exit

# no more arguments given
#
if [[ -z "$1" ]]; then
    if [[ "$removeif_only" = 'yes' ]]; then
        resetif  # just cleanup netifs
        exit
    fi

    # no argument - just display a list
    #
    if cd $confdir; then
        ls -l /etc/ | grep "$confdir"
    fi
    exit
fi

# extra argument exists
#
newconf="$1"
if [[ "$newconf" = 'templ.head' || "$newconf" = 'templ.tail' ]]; then
    echo "$0: You cannot change to '$newconf'"
    exit
elif [ ! -f "${confdir}/${newconf}/myname" ]; then
    echo "$0: no such conf - $newconf"
    exit
fi

# start of reconfiguration

# remove current files in /etc
#
if [[ -L /etc/myname ]]; then
    curconf=$(stat -f %Y /etc/myname)
    curconf=${curconf%/*}
    if [[ -n "$curconf" ]] && cd "$curconf"; then
        for f in *; do
            rm -f "/etc/$f"
        done
    elif [[ ! "$force_setup" = 'yes' ]]; then
        exit 1
    fi
fi

# check sprious hostname.if files
#
set -- /etc/hostname.*
if [[ -e "$1" ]]; then
    echo "$0: warning: extra hostname.if(s) found: $*"
    echo "Remove them manually if not needed."
fi


# collect file names to put into /etc
#
putfiles=$(ls -1d $confdir/{templ.{head,tail},$newconf}/* 2>/dev/null | sed -e 's/.*\///' | sort | uniq)

# link myname and copy other files to /etc
#
cd $confdir/$newconf || exit 1
for f in $putfiles; do
    if [[ "$f" = 'myname' ]]; then
        ln -sf $confdir/$newconf/myname /etc/myname
    else
        [[ -e "$f" ]] && cp -p "$f" /etc  # create a file with the same attribute
        : > "/etc/$f"                     # and make it empty

        # write the setting value with
        # concatenating head/tail template (if any)
        cat "${confdir}/templ.head/$f" \
            "$f" \
            "${confdir}/templ.tail/$f" >> "/etc/$f" 2>/dev/null
    fi
done

# perform -d option
#
if [[ "$relink_only" = 'yes' ]]; then
    exit
fi

# starting network by new configuration
#
resetif
hostname $(</etc/myname)
sh /etc/netstart
