#!/bin/sh

cd /

rm -f /tmp
mkdir /tmp
chmod 1777 /tmp

umount -f /mfs
ln -sf fuguita/usr .

rm -f /var
mkdir -p /var/run /var/log
touch /var/run/utmp /var/log/wtmp

rm -f /etc
mkdir -p /etc
> /etc/pwd.db

exec /fuguita/sbin/shutdown "$@"
